### GET ALL USERS
GET http://localhost:3001/api/user

### CREATE NEW USER
POST http://localhost:3001/api/user
content-type: application/json

{
    "username": "Janis Abols",
    "password": "password"
}


### REGISTER
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "Janis",
    "password": "password"
}


### LOGIN
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "Janis",
    "password": "password"
}


### 