const listsConstants = {
    REFRESH_ALL_REQUEST: 'LISTS_REFRESH_ALL_REQUEST',
    REFRESH_ALL_SUCCESS: 'LISTS_REFRESH_ALL_SUCCESS',
    REFRESH_ALL_FAILURE: 'LISTS_REFRESH_ALL_FAILURE'
};

export { listsConstants };