export const listsConstants = {
    REFRESH_ALL_REQUEST: 'LISTS_REFRESH_ALL_REQUEST',
    REFRESH_ALL_SUCCESS: 'LISTS_REFRESH_ALL_SUCCESS',
    REFRESH_ALL_FAILURE: 'LISTS_REFRESH_ALL_FAILURE',

    CREATE_LIST_REQUEST: 'LISTS_CREATE_LIST_REQUEST',
    CREATE_LIST_SUCCESS: 'LISTS_CREATE_LIST_SUCCESS',
    CREATE_LIST_FAILURE: 'LISTS_CREATE_LIST_FAILURE'
};