export const listsConstants = {
    SET_REFRESH_RATE: 'LISTS_SET_REFRESH_RATE',
    SET_SORT_OPTION: 'LISTS_SET_SORT_OPTION',

    REFRESH_ALL_REQUEST: 'LISTS_REFRESH_ALL_REQUEST',
    REFRESH_ALL_SUCCESS: 'LISTS_REFRESH_ALL_SUCCESS',
    REFRESH_ALL_FAILURE: 'LISTS_REFRESH_ALL_FAILURE',

    CREATE_LIST_REQUEST: 'LISTS_CREATE_LIST_REQUEST',
    CREATE_LIST_SUCCESS: 'LISTS_CREATE_LIST_SUCCESS',
    CREATE_LIST_FAILURE: 'LISTS_CREATE_LIST_FAILURE',

    CREATE_GROUP_REQUEST: 'LISTS_CREATE_GROUP_REQUEST',
    CREATE_GROUP_SUCCESS: 'LISTS_CREATE_GROUP_SUCCESS',
    CREATE_GROUP_FAILURE: 'LISTS_CREATE_GROUP_FAILURE',

    CREATE_ITEM_REQUEST: 'LISTS_CREATE_ITEM_REQUEST',
    CREATE_ITEM_SUCCESS: 'LISTS_CREATE_ITEM_SUCCESS',
    CREATE_ITEM_FAILURE: 'LISTS_CREATE_ITEM_FAILURE',

    UPDATE_LIST_REQUEST: 'LISTS_UPDATE_LIST_REQUEST',
    UPDATE_LIST_SUCCESS: 'LISTS_UPDATE_LIST_SUCCESS',
    UPDATE_LIST_FAILURE: 'LISTS_UPDATE_LIST_FAILURE',

    UPDATE_GROUP_REQUEST: 'LISTS_UPDATE_GROUP_REQUEST',
    UPDATE_GROUP_SUCCESS: 'LISTS_UPDATE_GROUP_SUCCESS',
    UPDATE_GROUP_FAILURE: 'LISTS_UPDATE_GROUP_FAILURE',

    UPDATE_ITEM_REQUEST: 'LISTS_UPDATE_ITEM_REQUEST',
    UPDATE_ITEM_SUCCESS: 'LISTS_UPDATE_ITEM_SUCCESS',
    UPDATE_ITEM_FAILURE: 'LISTS_UPDATE_ITEM_FAILURE',

    DELETE_LIST_REQUEST: 'LISTS_DELETE_LIST_REQUEST',
    DELETE_LIST_SUCCESS: 'LISTS_DELETE_LIST_SUCCESS',
    DELETE_LIST_FAILURE: 'LISTS_DELETE_LIST_FAILURE',

    DELETE_GROUP_REQUEST: 'LISTS_DELETE_GROUP_REQUEST',
    DELETE_GROUP_SUCCESS: 'LISTS_DELETE_GROUP_SUCCESS',
    DELETE_GROUP_FAILURE: 'LISTS_DELETE_GROUP_FAILURE',

    DELETE_ITEM_REQUEST: 'LISTS_DELETE_ITEM_REQUEST',
    DELETE_ITEM_SUCCESS: 'LISTS_DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE: 'LISTS_DELETE_ITEM_FAILURE',

    CREATE_LIST_LOCAL: 'LISTS_CREATE_LIST_LOCAL',
    CHANGE_LIST_LOCAL: 'LISTS_CHANGE_LIST_LOCAL',
    DELETE_LIST_LOCAL: 'LISTS_DELETE_LIST_LOCAL',

    CREATE_GROUP_LOCAL: 'LISTS_CREATE_GROUP_LOCAL',
    CHANGE_GROUP_LOCAL: 'LISTS_CHANGE_GROUP_LOCAL',
    DELETE_GROUP_LOCAL: 'LISTS_DELETE_GROUP_LOCAL',

    CREATE_ITEM_LOCAL: 'LISTS_CREATE_ITEM_LOCAL',
    CHANGE_ITEM_LOCAL: 'LISTS_CHANGE_ITEM_LOCAL',
    DELETE_ITEM_LOCAL: 'LISTS_DELETE_ITEM_LOCAL',
};