export const settingsConstants = {
    SET_REFRESH_RATE: 'LISTS_SET_REFRESH_RATE',
    SET_SORT_OPTION: 'LISTS_SET_SORT_OPTION',
    SET_SHOPPING_MODE: 'LISTS_SET_SHOPPING_MODE',
    SET_GLOBAL_SEARCH: 'LISTS_SET_GLOBAL_SEARCH',
};
