export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    LOGOUT_SUCCESS_LEGACY: 'USERS_LOGOUT_SUCCESS_LEGACY',

    ACCOUNT_DELETE_REQUEST: 'USERS_ACCOUNT_DELETE_REQUEST',
    ACCOUNT_DELETE_SUCCESS: 'USERS_ACCOUNT_DELETE_SUCCESS',
    ACCOUNT_DELETE_FAILURE: 'USERS_ACCOUNT_DELETE_FAILURE',

    JWT_LOCAL_STORAGE_KEY: 'USER',
    JWT_LOCAL_STORAGE_KEY_LEGACY: 'LANIS_PERSONAL',
};