### REGISTER USER 1 s
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "testuser1",
    "email": "test@user1.com",
    "password": "password",
    "firstName": "Test",
    "lastName": "User"
}

### LOGIN USER 1
POST http://localhost:3001/login
Content-Type: application/json

{ "username": "demouser", "password": "password" }

### REGISTER USER 2
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "testuser2",
    "email": "test@user2.com",
    "password": "password",
    "firstName": "Test",
    "lastName": "User"
}

### LOGIN USER 2
POST http://localhost:3001/login
Content-Type: application/json

{ "username": "testuser2", "password": "password" }
