name: Build and deploy to test environment

on:
  push:
    branches: 
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js version 14.x
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Build application
      run: |
        cd client
        npm run build --if-present
    
    - name: Create deployment package
      run: |
        mkdir -p ~/deployment/client
        cp -r client/build ~/deployment/client/
        cp -r server ~/deployment/
        cp package.json ~/deployment/
        cp package-lock.json ~/deployment/

    - name: Save private key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan jaab.dev >> ~/.ssh/known_hosts
    
    - name: Stop server app
      run: ssh github@jaab.dev "cd /var/www/test.jaab.dev && npm run test-stop --if-present"

    - name: Deploy package to server
      run: |
        ssh github@jaab.dev "cd /var/www/test.jaab.dev && rm -r node_modules"
        rsync -av --delete --exclude='server/.env' ~/deployment/ github@jaab.dev:/var/www/test.jaab.dev/
    
    - name: Install dependencies on server
      run: ssh github@jaab.dev "cd /var/www/test.jaab.dev && npm install"

    - name: Start server app
      run: ssh github@jaab.dev "cd /var/www/test.jaab.dev && npm run test-start --if-present"