# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build client app

on:
  push:
    branches: 
      - trunk
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js version 14.x
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    
    - name: Install dependencies
      run: |
        cd client
        npm ci

    - name: Build application
      run: |
        cd client
        npm run build --if-present

    - name: Save private key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to server
      run: |
        scp -i ~/.ssh/id_rsa -r client/build/ github@jaab.dev:/var/www/test.jaab.dev/